### ISSUE TITLE
运行后 文件夹是空的

### ISSUE THREAD

**Issue by dengxiaozhen** [focalhot/node.js-crawler#2]
![qq 20160624135303](https://cloud.githubusercontent.com/assets/8529528/16329152/2f50d0f2-3a13-11e6-9c60-266c2ec3f4dd.jpg)

**Comment by focalhot** [comment]
后来网易做了防采集功能

**Comment by mqliutie** [comment]
所以现在用不了了?网易做了防采集我不抓网易的不就好了,现在是我抓百度的图片都抓不到,是不是认为都不是美女啊- -

**Comment by focalhot** [comment]
更换了采集源，采中关村的图片
